# NLP: Sentiment analysis (v0)

ML Sample of Natural Language Processing.

- For environment test and confirmation.

## Dataset

Bag of Words Meets Bags of Popcorn
> Use Google's Word2Vec for movie reviews

https://www.kaggle.com/c/word2vec-nlp-tutorial

In [1]:
import pandas as pd

pd.set_option("display.max_colwidth", 140)

In [2]:
# Load Train Dataset
df_train = pd.read_csv(
    "./raw_data/labeledTrainData.tsv",
    delimiter="\t",
    na_filter=False
)

display(df_train)

,id,sentiment,review
0,5814_8,1,"With all this stuff going down at the moment with MJ i've started listening to his music, watching the odd documentary here and there, w..."
1,2381_9,1,"\The Classic War of the Worlds\"" by Timothy Hines is a very entertaining film that obviously goes to great effort and lengths to faithfu..."
2,7759_3,0,The film starts with a manager (Nicholas Bell) giving welcome investors (Robert Carradine) to Primal Park . A secret project mutating a ...
3,3630_4,0,"It must be assumed that those who praised this film (\the greatest filmed opera ever,\"" didn't I read somewhere?) either don't care for ..."
4,9495_8,1,"Superbly trashy and wondrously unpretentious 80's exploitation, hooray! The pre-credits opening sequences somewhat give the false impres..."
...,...,...,...
24995,3453_3,0,It seems like more consideration has gone into the IMDb reviews of this film than went into the source.<br /><br />Here's a review witho...
24996,5064_1,0,"I don't believe they made this film. Completely unnecessary. The first film was okay. But there was no need for a sequel, certainly not ..."
24997,10905_3,0,"Guy is a loser. Can't get girls, needs to build up, is picked on by stronger more successful guys, etc. Seen it, saw it, moved on. I'd h..."
24998,10194_3,0,"This 30 minute documentary Buñuel made in the early 1930's about one of Spain's poorest regions is, in my opinion, one of his weakest fi..."
24999,8478_8,1,I saw this movie as a child and it broke my heart! No other story had such a unfinished ending... I grew up on many great anime movies a...

In [3]:
# Load Test Dataset
df_test = pd.read_csv(
    "./raw_data/testData.tsv",
    delimiter="\t",
    na_filter=False
)

display(df_test)

,id,review
0,12311_10,"Naturally in a film who's main themes are of mortality, nostalgia, and loss of innocence it is perhaps not surprising that it is rated m..."
1,8348_2,"This movie is a disaster within a disaster film. It is full of great action scenes, which are only meaningful if you throw away all sens..."
2,5828_4,"All in all, this is a movie for kids. We saw it tonight and my child loved it. At one point my kid's excitement was so great that sittin..."
3,7186_2,"Afraid of the Dark left me with the impression that several different screenplays were written, all too short for a feature length film,..."
4,12128_7,"A very accurate depiction of small time mob life filmed in New Jersey. The story, characters and script are believable but the acting dr..."
...,...,...
24995,2155_10,"Sony Pictures Classics, I'm looking at you! Sony's got the rights to Harry records -- you need to distribute the film and you'll get rad..."
24996,59_10,"I always felt that Ms. Merkerson had never gotten a role fitting her skills. Familiar to millions as the Lt. on Law and Order, she has b..."
24997,2531_1,"I was so disappointed in this movie. I am very familiar with the case, having read not only Mark Fuhrman's book but also the far superio..."
24998,7772_8,"From the opening sequence, filled with black and white shots reminiscent of Gordan Parks photos, this film draws the viewer into a feeli..."
24999,11465_10,This is a great horror film for people who don't want all that vomit-retching gore and sensationalism. This movie has equal amounts of h...

In [4]:
# Load Sample Dataset
df_sample = pd.read_csv(
    "./raw_data/sampleSubmission.csv"
)

display(df_sample)

             id  sentiment
0      12311_10          0
1        8348_2          0
2        5828_4          0
3        7186_2          0
4       12128_7          0
...         ...        ...
24995   2155_10          0
24996     59_10          0
24997    2531_1          0
24998    7772_8          0
24999  11465_10          0

[25000 rows x 2 columns]