In [1]:
import pandas_datareader as pdr
pdr.get_data_fred('GS10')

            GS10
DATE
2018-01-01  2.58
2018-02-01  2.86
2018-03-01  2.84
2018-04-01  2.87
2018-05-01  2.98
2018-06-01  2.91
2018-07-01  2.89
2018-08-01  2.89
2018-09-01  3.00
2018-10-01  3.15
2018-11-01  3.12
2018-12-01  2.83
2019-01-01  2.71
2019-02-01  2.68
2019-03-01  2.57
2019-04-01  2.53
2019-05-01  2.40
2019-06-01  2.07
2019-07-01  2.06
2019-08-01  1.63
2019-09-01  1.70
2019-10-01  1.71
2019-11-01  1.81
2019-12-01  1.86
2020-01-01  1.76
2020-02-01  1.50
2020-03-01  0.87
2020-04-01  0.66
2020-05-01  0.67
2020-06-01  0.73
2020-07-01  0.62
2020-08-01  0.65
2020-09-01  0.68
2020-10-01  0.79
2020-11-01  0.87
2020-12-01  0.93
2021-01-01  1.08
2021-02-01  1.26
2021-03-01  1.61
2021-04-01  1.64
2021-05-01  1.62
2021-06-01  1.52
2021-07-01  1.32
2021-08-01  1.28
2021-09-01  1.37
2021-10-01  1.58
2021-11-01  1.56
2021-12-01  1.47
2022-01-01  1.76
2022-02-01  1.93
2022-03-01  2.13
2022-04-01  2.75
2022-05-01  2.90
2022-06-01  3.14
2022-07-01  2.90
2022-08-01  2.90
2022-09-01  3.52
2022-10-01  3.98
2022-11-01  3.89